### ISSUE TITLE
피드백 - 김병연 튜터

### ISSUE THREAD

**Issue by ByungyeonKim** [G-NooN/cineDocs#1]
전반적으로 웹 개발 이해도가 높으신 것 같습니다. 파일 구조부터 전체적인 코드까지 깔끔하게 잘 작성해주셨네요. 모듈 또한 적당한 크기로 잘 나누셔서 금방 이해할 수 있었습니다.

## HTML

시멘틱 태그도 적절하게 잘 사용해주셨고, 주석까지..깔끔합니다. 여기서 딱 하나가 있다면 `html` 태그에 `lang` 속성을 포함하여 페이지의 언어에 대한 정보를 명시적으로 정의하는 것이 좋습니다. 일부 번역 도구에는 `lang` 속성을 사용해서 페이지가 다른 언어로 번역 되어야 할지 여부를 결정하기도 하고, 스크린 리더와 접근성에도 영향이 있습니다.

https://github.com/G-NooN/cineDocs/blob/3a65d3b81e163a1d90cf7d7e474564fa4e1542dd/index.html#L2

## JS

DOM API를 정말 다양하게 사용하셨군요. 구조 분해 할당까지 쓰신 것을 보니 어느 정도 숙련이 되신 것 같습니다. 

https://github.com/G-NooN/cineDocs/blob/3a65d3b81e163a1d90cf7d7e474564fa4e1542dd/src/search.js#L2-L16

특히 영화의 검색 결과를 보여주는 코드를 보고 깜짝 놀랐습니다. 정말 인상 깊었습니다. 👍

## CSS

프레임워크/라이브러리의 도움 없이 순수 CSS만으로 스타일링도 잘해주셨습니다. reset.css로 브라우저의 기본 스타일까지 초기화를 잘 해주셨네요. 모바일 화면에서 헤더의 레이아웃이 약간 깨지는 것을 제외하곤 반응형도 잘 구현해주셨습니다.

## 사용자 경험

영화의 검색 결과가 없을 때 현재는 빈화면만 표시가 됩니다. 사용자에게 관련 영화가 없다는 것을 알려주면 더 좋을 것 같습니다.

---

사실 피드백을 드릴만 한 것들이 뭐..거의 없습니다. 정말 고생하셨습니다. 👏 남은 기간도 함께 힘냈으면 좋겠습니다. 💪

**Comment by G-NooN** [comment]
해설 강의와 다른 분들의 코드를 참조했던 부분이 정말 크게 작용했습니다.
저 또한 프로젝트를 진행하면서 개선과 발전이 필요하다고 느낀 부분들을 많이 발견할 수 있었고, 또 많이 배울 수 있었습니다.
피드백 정말 감사합니다.
